#ifndef __H_SOLUTION_ERROR_H__
#define __H_SOLUTION_ERROR_H__

#define HSOLUTION_SUCCESS                       0

// VERIFY INTEGRITY ERROR
#define HSOLUTION_ERR_VERIFY_INTEGRITY          1000
#define HSOLUTION_ERR_SOCK_ERR                  (HSOLUTION_ERR_VERIFY_INTEGRITY + 1)
#define HSOLUTION_ERR_CONNECT_ERR               (HSOLUTION_ERR_VERIFY_INTEGRITY + 2)
#define HSOLUTION_ERR_SEND_ERR                  (HSOLUTION_ERR_VERIFY_INTEGRITY + 3)
#define HSOLUTION_ERR_RECV_ERR                  (HSOLUTION_ERR_VERIFY_INTEGRITY + 4)
#define HSOLUTION_ERR_VERIFY_ERR                (HSOLUTION_ERR_VERIFY_INTEGRITY + 5)

// EDGE ASYM
#define HSOLUTION_ERR_ASYM                      2000
#define HSOLUTION_ERR_ASYM_GEN_KEY_PAIR         (HSOLUTION_ERR_ASYM + 1)
#define HSOLUTION_ERR_ASYM_DEC                  (HSOLUTION_ERR_ASYM + 2)

// EDGE SYMM
#define HSOLUTION_ERR_SYMM                      3000
#define HSOLUTION_ERR_SYMM_ENC                  (HSOLUTION_ERR_SYMM + 1)
#define HSOLUTION_ERR_SYMM_DEC                  (HSOLUTION_ERR_SYMM + 2)

#endif
