/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hSolution */

#ifndef _Included_hSolution
#define _Included_hSolution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hSolution
 * Method:    errorPrint
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tpcstld_twozerogame_hSolution_errorPrint
  (JNIEnv *env, jobject obj, jint ret, jint socket_num);

/*
 * Class:     hSolution
 * Method:    verifyIntegrity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tpcstld_twozerogame_hSolution_verifyIntegrity
  (JNIEnv *env, jobject obj, jstring signData);

/*
 * Class:     hSolution
 * Method:    InitCrypto
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tpcstld_twozerogame_hSolution_InitCrypto
  (JNIEnv* env, jobject obj, jstring _signPath);


#ifdef __cplusplus
}
#endif
#endif
